# Based on Ubuntu 18.04
FROM ubuntu:18.04
MAINTAINER Gianmauro Cuccuru <gmauro@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
 && apt-get install -q --no-install-recommends -y \
    apt-utils \
    apt-transport-https \
    wget \
    nano \
    git \
    build-essential \
    python-pip \
    python-dev \
 && apt-get autoremove \
 && apt-get clean


RUN git clone --recursive -b stable-2.7 https://github.com/ansible/ansible \
 && cd ./ansible \
 && pip install --upgrade packaging \
 && pip install --upgrade setuptools \
 && pip install --upgrade -r ./requirements.txt \
 && make \
 && make install \
 && cd .. \
 && rm -rf ansible
